name: The Meta Alchemy Association
favicon: null
layout_spectrum: 0.49115
typography_spectrum: 1
title: The Meta Alchemy Association
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ffcb35'
    - '#342f28'
    - '#716d62'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.8888823217712343
  rhythmicContrast: 0.75
purpose: []
